### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alexggordon** [mkandalf/crust#14]
Hello!

So I noticed that there doesn't seem to be a license anywhere in the repository. I was considering using this for a project, but depending on the license, I'm not sure if I can. Would you mind adding one and letting me know? thanks!

Alex

**Comment by mkandalf** [comment]
Hi Alex,

aded1a52c5271caaa59dfb89442f9e2268bda08b adds the MIT license to the project. Hopefully that addresses any concerns you had. Drop me a line if you do something with it, and feel free to send any pull requests!

Also, note that you'll need to do some minor fixes to get it updated to 1.0-alpha.

Nick

**Comment by mkandalf** [comment]
@alexggordon I just pushed fixes for rustc 1.0.0-nightly (44a287e6e 2015-01-08 17:03:40 -0800), although quite a few warnings now, including lots of ints and uints lying around.

**Comment by alexggordon** [comment]
Sounds good. I'd like to use this library for a project I'm working on, so I'll work on it tonight and see what I can fix. I'll let you know what I run into!
